### ISSUE TITLE
Catching exceptions not supported

### ISSUE THREAD

**Issue by neobrain** [devkitPro/buildscripts#4] opened 2015-10-22 00:03 UTC
Trying to run this trivial 3DS program (which is a minimal modification to ctrulib's hello-world example) on actual hardware causes a crash:

```
#include <ios>
#include <iostream>
#include <cstdio>

#include <3ds.h>

int main(int argc, char **argv)
{
	gfxInitDefault();
	consoleInit(GFX_TOP, NULL);

        try {
            throw std::string("hi");
        }catch(std::string a) {
            std::cout << a << std::endl;
        }

	while (aptMainLoop())
	{
		hidScanInput();
		u32 kDown = hidKeysDown();
		if (kDown & KEY_START) break;

		gfxFlushBuffers();
		gfxSwapBuffers();

		gspWaitForVBlank();
	}

	gfxExit();
	return 0;
}
```

This program will print
```
terminate called after throwing an instance of 'std::string'
terminate called recursively
```
to the screen and then hang indefinitely.

The issue can be reproduced in the emulator Citra.

**Comment by neobrain** [comment] 2015-10-22 11:57
Further testing shows an interesting thing: Running .3dsx files in Citra produces the crash described above, while using an equivalent .elf works just fine.

**Comment by neobrain** [comment] 2015-10-22 13:03
Having read into exception handling in GCC, I think the reason for the crash may be that the .eh_frame section is being thrown away in 3dstool when converting .elf files to .3dsx.

**Comment by fincs** [comment] 2015-10-25 11:38
Adding or removing the eh_frame section in the linker script doesn't appear to affect anything. I manually checked the generated 3dsx and it appears to be there, in the data segment.

**Comment by neobrain** [comment] 2015-10-25 11:42
@fincs Sorry, I forgot updating the issue report: It seems that on ARM, gcc actually generated exception information using the .extab and .exidx sections: https://wiki.linaro.org/KenWerner/Sandbox/libunwind?action=AttachFile&do=get&target=libunwind-LDS.pdf

**Comment by fincs** [comment] 2015-10-25 15:21
Alright, see this: https://github.com/devkitPro/3dstools/commit/47bea18f5cded3437552e3af968aa1356e2d6f3e

The problem is fixed.

**Comment by WinterMute** [comment] 2015-12-14 18:15
fixed with r45 release

**Closed by WinterMute** 2015-12-14 18:15 UTC

**Comment by neobrain** [comment] 2015-12-14 18:17
Thanks, guys :)
